language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.15.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install:
  - "sudo apt-get install libnotify4"
  - "gem install bundler"
