# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{libnotify}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Suschlik"]
  s.date = %q{2010-02-16}
  s.email = %q{peter-libnotify@suschlik.de}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/libnotify.rb",
     "libnotify.gemspec",
     "test.watchr",
     "test/helper.rb",
     "test/test_libnotify.rb"
  ]
  s.homepage = %q{http://github.com/splattael/libnotify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby bindings for libnotify using FFI}
  s.test_files = [
    "test/test_libnotify.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0.6.2"])
      s.add_development_dependency(%q<riot>, [">= 0.1.12.pre"])
      s.add_development_dependency(%q<riot_notifier>, [">= 0.0.7"])
    else
      s.add_dependency(%q<ffi>, [">= 0.6.2"])
      s.add_dependency(%q<riot>, [">= 0.1.12.pre"])
      s.add_dependency(%q<riot_notifier>, [">= 0.0.7"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0.6.2"])
    s.add_dependency(%q<riot>, [">= 0.1.12.pre"])
    s.add_dependency(%q<riot_notifier>, [">= 0.0.7"])
  end
end

